hash-format = "sha256"

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-view.pw.toml"
metafile = true

[[files]]
file = "mods/entity-collision-fps-fix.pw.toml"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
metafile = true

[[files]]
file = "mods/fastsuite.pw.toml"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.pw.toml"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
metafile = true

[[files]]
file = "mods/pluto.pw.toml"
metafile = true

[[files]]
file = "mods/radon.pw.toml"
metafile = true
