name = "Berd Pack"
author = "Chris Kay <chris@cjkay.com>"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"

[options]
no-internal-hashes = true
