name: "Build modpacks"
on:
  workflow_call:
jobs:
  build-modpacks:
    name: "Build modpacks"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
          cache: false
      - run: go install "github.com/packwiz/packwiz@9bddd21"
      - run: packwiz curseforge export --side client -o "Berd-Pack-Client.zip"
      - run: packwiz curseforge export --side server -o "Berd-Pack-Server.zip"
      - run: packwiz modrinth export -o "Berd-Pack.mrpack"
      - uses: actions/upload-artifact@v3
        with:
          name: modpacks
          if-no-files-found: error
          path: |
            Berd-Pack-*.zip
            Berd-Pack.mrpack
