name: "Lint commit messages"
on:
  workflow_call:
jobs:
  lint-commit-messages:
    name: "Lint commit messages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
