name: "Push"
on:
  push:
    branches:
      - "main"
permissions:
  contents: write
jobs:
  build-modpacks:
    name: "Build modpacks"
    uses: "./.github/workflows/build-modpacks.yml"
  publish-release:
    name: "Publish release"
    needs: build-modpacks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
          cache: false
      - run: go install "github.com/packwiz/packwiz@9bddd21"
      - uses: cycjimmy/semantic-release-action@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @google/semantic-release-replace-plugin
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            conventional-changelog-conventionalcommits
